openapi: 3.0.0
info:
  title: Apex Legends Ranked Map Plugin
  description: Plugin to identify the current Apex Legends ranked map.
  version: 1.0.0
servers:
  - url: http://localhost:5003
paths:
  /apex/ranked-map:
    get:
      summary: Get the current ranked map
      operationId: getRankedMap
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
  /apex/get-future-map:
    get:
      summary: returns the current map and calculates future map changes
      operationId: getMapInfo
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_map:
                    type: string
                  map_rotation:
                    type: array
                    items:
                      type: string
                  change_time:
                    type: string
                  map_change:
                    type: string